external-controller: 127.0.0.1:9090
geodata-mode: true

port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info

load: &load
  type: load-balance
  use:
    - Remote
  url: 'https://www.gstatic.com/generate_204'
  interval: 300

proxy-providers:

  Remote:
    type: http  #æ”¯æŒæœºåœºé€šç”¨è®¢é˜…
    url: 'https://www.gstatic.com/generate_204'
    interval: 3600
    path: "./Providers/Proxy/Remote.yaml"
    health-check:
      enable: true
      interval: 1200
      url: https://gstatic.com/generate_204

        #Local:
        #type: file  #æ”¯æŒè§£æèŠ‚ç‚¹åˆ†äº«æ ¼å¼ï¼Œæ–°å»ºå¹¶å¡«å†™åœ¨Local.yamlå³å¯
        #path: "./Providers/Proxy/Local.yaml"
        #health-check:
        #enable: true
        #interval: 1200
        #url: https://gstatic.com/generate_204

proxy-groups:

  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸŒ€ æ‰‹åŠ¨åˆ‡æ¢

  - name: ğŸŒ€ æ‰‹åŠ¨åˆ‡æ¢
    type: select
    use:
      - Remote

  - name: ğŸ¥ å¥ˆé£è§†é¢‘
    type: select
    proxies:
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸŒ€ æ‰‹åŠ¨åˆ‡æ¢

  - name: ğŸƒ å¹¿å‘Šæ‹¦æˆª
    type: select
    proxies:
      - REJECT
      - DIRECT

  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    <<: *load
    filter: 'é¦™æ¸¯'

  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
    <<: *load
    filter: 'å°æ¹¾'

  - name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
    <<: *load
    filter: 'ç‹®åŸ|æ–°åŠ å¡'

  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    <<: *load
    filter: 'æ—¥æœ¬'

  - name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹
    <<: *load
    filter: 'éŸ©å›½'

  - name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
    <<: *load
    filter: 'ç¾å›½'

rules:
  - GEOSITE,category-ads-all,ğŸƒ å¹¿å‘Šæ‹¦æˆª
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,google-cn,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,cn,DIRECT
  - GEOSITE,geolocation-!cn,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - GEOIP,TELEGRAM,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - GEOIP,NETFLIX,ğŸ¥ å¥ˆé£è§†é¢‘
  - GEOIP,CN,DIRECT
  - MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
